# Generated by Django 3.0 on 2020-05-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discout_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
