# Generated by Django 3.0 on 2020-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200507_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
