# Generated by Django 3.0 on 2020-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200511_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteritem',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
    ]
