# Generated by Django 3.0 on 2020-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200511_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ManyToManyField(to='core.ImageItem', verbose_name='Изображение'),
        ),
    ]
