# Generated by Django 3.0 on 2020-05-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_item',
            field=models.CharField(choices=[('N', 'Новинка'), ('H', 'Горячее')], default='N', max_length=1, verbose_name='Лэйбл'),
            preserve_default=False,
        ),
    ]
