# Generated by Django 3.0 on 2020-05-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200512_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='core.Item', verbose_name='Товара'),
        ),
    ]
