# Generated by Django 3.0 on 2020-05-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200512_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_item',
            field=models.CharField(choices=[('primary', 'Новинка'), ('danger', 'Горячее')], max_length=10, verbose_name='Лэйбл'),
        ),
    ]
